import { AsyncLocalStorage } from 'node:async_hooks';

/**
 * Per-request facts the audit trail needs (correlation id, network origin, acting user) without
 * threading them through every service signature. Populated by the requestContext middleware; the
 * requestId is ALWAYS generated by the server — a client-supplied X-Request-Id is never trusted.
 */
export interface RequestContext {
	requestId: string;
	ipAddress: string | null;
	userAgent: string | null;
	actorUserId: number | null;
}

const storage = new AsyncLocalStorage<RequestContext>();

export const runWithRequestContext = <T>(ctx: RequestContext, fn: () => T): T =>
	storage.run(ctx, fn);
export const getRequestContext = (): RequestContext | undefined => storage.getStore();

/** Called once the caller is authenticated (requireAuth / login) so later audit rows name the actor. */
export function setContextActor(userId: number | null) {
	const ctx = storage.getStore();
	if (ctx) ctx.actorUserId = userId;
}
