import { Prisma } from '@prisma/client';
import { prisma } from '../config/prisma.js';
import { getRequestContext, type RequestContext } from '../lib/requestContext.js';
import { buildChanges, sanitizeForAudit } from '../lib/auditRedaction.js';

/**
 * THE single writer of audit events. Domain services call `writeAuditEvent(tx, …)` with the SAME
 * transaction client as the state change, so a rollback leaves no "success" event behind. There is
 * no update/delete API for audit rows anywhere in the application.
 */
export type AuditDb = Prisma.TransactionClient | typeof prisma;

/** Stable action codes (MODULE.ACTION). Kept deliberately small. */
export const AuditAction = {
	AUTH_LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',
	AUTH_LOGOUT: 'AUTH.LOGOUT',
	AUTH_PASSWORD_CHANGED: 'AUTH.PASSWORD_CHANGED',

	USER_CREATED: 'USER.CREATED',
	USER_UPDATED: 'USER.UPDATED',
	USER_DISABLED: 'USER.DISABLED',
	USER_ENABLED: 'USER.ENABLED',
	USER_ROLE_CHANGED: 'USER.ROLE_CHANGED',

	ROLE_CREATED: 'ROLE.CREATED',
	ROLE_UPDATED: 'ROLE.UPDATED',
	ROLE_PERMISSIONS_CHANGED: 'ROLE.PERMISSIONS_CHANGED',

	ORG_CREATED: 'ORG.CREATED',
	ORG_UPDATED: 'ORG.UPDATED',
	POSITION_CREATED: 'POSITION.CREATED',
	POSITION_UPDATED: 'POSITION.UPDATED',

	EMPLOYEE_CREATED: 'EMPLOYEE.CREATED',
	EMPLOYEE_UPDATED: 'EMPLOYEE.UPDATED',
	EMPLOYEE_TRANSFERRED: 'EMPLOYEE.TRANSFERRED',
	EMPLOYEE_STATUS_CHANGED: 'EMPLOYEE.STATUS_CHANGED',
	EMPLOYEE_USER_LINK_CHANGED: 'EMPLOYEE.USER_LINK_CHANGED',

	SHIFT_CREATED: 'SHIFT.CREATED',
	SHIFT_UPDATED: 'SHIFT.UPDATED',
	SHIFT_DISABLED: 'SHIFT.DISABLED',
	HOLIDAY_CREATED: 'HOLIDAY.CREATED',
	HOLIDAY_UPDATED: 'HOLIDAY.UPDATED',
	WORK_LOCATION_CREATED: 'WORK_LOCATION.CREATED',
	WORK_LOCATION_UPDATED: 'WORK_LOCATION.UPDATED',
	SCHEDULE_ASSIGNED: 'SCHEDULE.ASSIGNED',
	SCHEDULE_UPDATED: 'SCHEDULE.UPDATED',
	POLICY_UPDATED: 'POLICY.UPDATED',

	ATTENDANCE_CHECK_IN: 'ATTENDANCE.CHECK_IN',
	ATTENDANCE_CHECK_OUT: 'ATTENDANCE.CHECK_OUT',
	ATTENDANCE_CORRECTION_REQUESTED: 'ATTENDANCE.CORRECTION_REQUESTED',
	ATTENDANCE_STEP_APPROVED: 'ATTENDANCE.APPROVAL_STEP_APPROVED',
	ATTENDANCE_APPROVED: 'ATTENDANCE.APPROVED',
	ATTENDANCE_REJECTED: 'ATTENDANCE.REJECTED',
	ATTENDANCE_CANCELLED: 'ATTENDANCE.CANCELLED',

	LEAVE_TYPE_CREATED: 'LEAVE_TYPE.CREATED',
	LEAVE_TYPE_UPDATED: 'LEAVE_TYPE.UPDATED',
	LEAVE_BALANCE_CREATED: 'LEAVE_BALANCE.CREATED',
	LEAVE_BALANCE_UPDATED: 'LEAVE_BALANCE.UPDATED',
	LEAVE_BALANCE_ADJUSTED: 'LEAVE_BALANCE.ADJUSTED',

	LEAVE_REQUESTED: 'LEAVE.REQUESTED',
	LEAVE_STEP_APPROVED: 'LEAVE.APPROVAL_STEP_APPROVED',
	LEAVE_APPROVED: 'LEAVE.APPROVED',
	LEAVE_REJECTED: 'LEAVE.REJECTED',
	LEAVE_CANCELLED: 'LEAVE.CANCELLED',

	OVERTIME_REQUESTED: 'OVERTIME.REQUESTED',
	OVERTIME_STEP_APPROVED: 'OVERTIME.APPROVAL_STEP_APPROVED',
	OVERTIME_APPROVED: 'OVERTIME.APPROVED',
	OVERTIME_REJECTED: 'OVERTIME.REJECTED',
	OVERTIME_CANCELLED: 'OVERTIME.CANCELLED',

	APPROVAL_WORKFLOW_CHANGED: 'APPROVAL.WORKFLOW_CHANGED',
	APPROVAL_STEP_APPROVED: 'APPROVAL.STEP_APPROVED',
	APPROVAL_STEP_REJECTED: 'APPROVAL.STEP_REJECTED',
	APPROVAL_STEP_REASSIGNED: 'APPROVAL.STEP_REASSIGNED',

	PAYROLL_SETTINGS_UPDATED: 'PAYROLL.SETTINGS_UPDATED',
	PAY_COMPONENT_CREATED: 'PAY_COMPONENT.CREATED',
	PAY_COMPONENT_UPDATED: 'PAY_COMPONENT.UPDATED',
	COMPENSATION_CREATED: 'COMPENSATION.CREATED',
	COMPENSATION_CHANGED: 'COMPENSATION.CHANGED',
	RECURRING_PAY_COMPONENT_ASSIGNED: 'RECURRING_PAY_COMPONENT.ASSIGNED',
	RECURRING_PAY_COMPONENT_ENDED: 'RECURRING_PAY_COMPONENT.ENDED',
	PAYROLL_PERIOD_CREATED: 'PAYROLL.PERIOD_CREATED',
	PAYROLL_PERIOD_UPDATED: 'PAYROLL.PERIOD_UPDATED',
	PAYROLL_RUN_CREATED: 'PAYROLL.RUN_CREATED',
	PAYROLL_RUN_CALCULATED: 'PAYROLL.RUN_CALCULATED',
	PAYROLL_RUN_FINALIZED: 'PAYROLL.RUN_FINALIZED',
	PAYROLL_MANUAL_ADJUSTMENT_ADDED: 'PAYROLL.MANUAL_ADJUSTMENT_ADDED',
	// Phase 13 — payroll approval (ids / attempt / versions only, never amounts)
	PAYROLL_RUN_SUBMITTED: 'PAYROLL.RUN_SUBMITTED',
	PAYROLL_RUN_STEP_APPROVED: 'PAYROLL.RUN_APPROVAL_STEP_APPROVED',
	PAYROLL_RUN_APPROVED: 'PAYROLL.RUN_APPROVED',
	PAYROLL_RUN_REJECTED: 'PAYROLL.RUN_REJECTED',
	PAYROLL_RUN_APPROVAL_CANCELLED: 'PAYROLL.RUN_APPROVAL_CANCELLED',
	PAYROLL_RUN_REOPENED: 'PAYROLL.RUN_REOPENED',
	// Phase 13 — payslips
	PAYSLIP_CREATED: 'PAYSLIP.CREATED',
	PAYSLIP_BATCH_CREATED: 'PAYSLIP.BATCH_CREATED',
	// Phase 14 — bank accounts (bankCode / currency / last4 / changed flags only — never the number)
	EMPLOYEE_PAYMENT_PROFILE_UPDATED: 'EMPLOYEE_PAYMENT_PROFILE.UPDATED',
	EMPLOYEE_BANK_ACCOUNT_CREATED: 'EMPLOYEE_BANK_ACCOUNT.CREATED',
	EMPLOYEE_BANK_ACCOUNT_UPDATED: 'EMPLOYEE_BANK_ACCOUNT.UPDATED',
	EMPLOYEE_BANK_ACCOUNT_ACTIVATED: 'EMPLOYEE_BANK_ACCOUNT.ACTIVATED',
	EMPLOYEE_BANK_ACCOUNT_DEACTIVATED: 'EMPLOYEE_BANK_ACCOUNT.DEACTIVATED',
	// Phase 14 — payroll payment (ids / counts / status only — never amounts or account numbers)
	PAYROLL_PAYMENT_BATCH_CREATED: 'PAYROLL_PAYMENT.BATCH_CREATED',
	PAYROLL_PAYMENT_BATCH_REBUILT: 'PAYROLL_PAYMENT.BATCH_REBUILT',
	PAYROLL_PAYMENT_BATCH_VALIDATED: 'PAYROLL_PAYMENT.BATCH_VALIDATED',
	PAYROLL_PAYMENT_EXPORTED: 'PAYROLL_PAYMENT.EXPORTED',
	PAYROLL_PAYMENT_EXPORT_DOWNLOADED: 'PAYROLL_PAYMENT.EXPORT_DOWNLOADED',
	PAYROLL_PAYMENT_ITEM_PAID: 'PAYROLL_PAYMENT.ITEM_PAID',
	PAYROLL_PAYMENT_ITEM_FAILED: 'PAYROLL_PAYMENT.ITEM_FAILED',
	PAYROLL_PAYMENT_BATCH_CANCELLED: 'PAYROLL_PAYMENT.BATCH_CANCELLED',
	BANK_EXPORT_PROFILE_CREATED: 'BANK_EXPORT_PROFILE.CREATED',
	BANK_EXPORT_PROFILE_UPDATED: 'BANK_EXPORT_PROFILE.UPDATED',
	// Phase 15 — reconciliation / reversal / retry (ids / counts / status / file hash only — never
	// amounts, account numbers, raw bank rows or free-text reasons)
	PAYROLL_PAYMENT_RECONCILIATION_IMPORTED: 'PAYROLL_PAYMENT.RECONCILIATION_IMPORTED',
	PAYROLL_PAYMENT_RECONCILIATION_ROW_MATCHED: 'PAYROLL_PAYMENT.RECONCILIATION_ROW_MATCHED',
	PAYROLL_PAYMENT_RECONCILIATION_ROW_IGNORED: 'PAYROLL_PAYMENT.RECONCILIATION_ROW_IGNORED',
	PAYROLL_PAYMENT_RECONCILIATION_APPLIED: 'PAYROLL_PAYMENT.RECONCILIATION_APPLIED',
	PAYROLL_PAYMENT_RECONCILIATION_CANCELLED: 'PAYROLL_PAYMENT.RECONCILIATION_CANCELLED',
	PAYROLL_PAYMENT_ITEM_REVERSED: 'PAYROLL_PAYMENT.ITEM_REVERSED',
	PAYROLL_PAYMENT_RETRY_BATCH_CREATED: 'PAYROLL_PAYMENT.RETRY_BATCH_CREATED',
	RECONCILIATION_PROFILE_CREATED: 'RECONCILIATION_PROFILE.CREATED',
	RECONCILIATION_PROFILE_UPDATED: 'RECONCILIATION_PROFILE.UPDATED',
	// Phase 16 — payroll accounting (metadata: ids / counts / status only — never amounts)
	PAYROLL_ACCOUNTING_JOURNAL_CREATED: 'PAYROLL_ACCOUNTING.JOURNAL_CREATED',
	PAYROLL_ACCOUNTING_JOURNAL_VALIDATED: 'PAYROLL_ACCOUNTING.JOURNAL_VALIDATED',
	PAYROLL_ACCOUNTING_JOURNAL_POSTED: 'PAYROLL_ACCOUNTING.JOURNAL_POSTED',
	PAYROLL_ACCOUNTING_JOURNAL_CANCELLED: 'PAYROLL_ACCOUNTING.JOURNAL_CANCELLED',
	PAYROLL_ACCOUNTING_JOURNAL_EXPORTED: 'PAYROLL_ACCOUNTING.JOURNAL_EXPORTED',
	PAYROLL_ACCOUNTING_EXPORT_DOWNLOADED: 'PAYROLL_ACCOUNTING.EXPORT_DOWNLOADED',
	PAYROLL_ACCOUNTING_RULESET_CREATED: 'PAYROLL_ACCOUNTING.RULESET_CREATED',
	PAYROLL_ACCOUNTING_RULESET_UPDATED: 'PAYROLL_ACCOUNTING.RULESET_UPDATED',
	PAYROLL_ACCOUNTING_RULESET_ACTIVATED: 'PAYROLL_ACCOUNTING.RULESET_ACTIVATED',
	PAYROLL_ACCOUNTING_RULESET_DEACTIVATED: 'PAYROLL_ACCOUNTING.RULESET_DEACTIVATED',
	PAYROLL_ACCOUNTING_MAPPING_UPDATED: 'PAYROLL_ACCOUNTING.MAPPING_UPDATED',
	PAYROLL_ACCOUNTING_GL_ACCOUNT_CREATED: 'PAYROLL_ACCOUNTING.GL_ACCOUNT_CREATED',
	PAYROLL_ACCOUNTING_GL_ACCOUNT_UPDATED: 'PAYROLL_ACCOUNTING.GL_ACCOUNT_UPDATED',
	PAYROLL_ACCOUNTING_EXPORT_PROFILE_CREATED: 'PAYROLL_ACCOUNTING.EXPORT_PROFILE_CREATED',
	PAYROLL_ACCOUNTING_EXPORT_PROFILE_UPDATED: 'PAYROLL_ACCOUNTING.EXPORT_PROFILE_UPDATED',
	PAYROLL_SCHEDULE_CREATED: 'PAYROLL_SCHEDULE.CREATED',
	PAYROLL_SCHEDULE_UPDATED: 'PAYROLL_SCHEDULE.UPDATED',
	PAYROLL_SCHEDULE_PERIODS_GENERATED: 'PAYROLL_SCHEDULE.PERIODS_GENERATED',
	PAYROLL_RULE_CREATED: 'PAYROLL_RULE.CREATED',

	STATUTORY_RULE_CREATED: 'STATUTORY_RULE.CREATED',
	STATUTORY_RULE_ACTIVATED: 'STATUTORY_RULE.ACTIVATED',
	EMPLOYEE_STATUTORY_PROFILE_UPDATED: 'EMPLOYEE_STATUTORY_PROFILE.UPDATED',
	PAY_COMPONENT_STATUTORY_TREATMENT_UPDATED: 'PAY_COMPONENT.STATUTORY_TREATMENT_UPDATED',

	// Phase 17B
	REPORT_EXPORTED: 'REPORT.EXPORTED'
} as const;
export type AuditActionCode = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntity = {
	USER: 'USER',
	ROLE: 'ROLE',
	EMPLOYEE: 'EMPLOYEE',
	SHIFT: 'SHIFT',
	HOLIDAY: 'HOLIDAY',
	WORK_LOCATION: 'WORK_LOCATION',
	SCHEDULE_ASSIGNMENT: 'SCHEDULE_ASSIGNMENT',
	POLICY: 'POLICY',
	ORGANIZATION: 'ORGANIZATION',
	POSITION: 'POSITION',
	ATTENDANCE: 'ATTENDANCE',
	ATTENDANCE_CORRECTION: 'ATTENDANCE_CORRECTION',
	LEAVE_REQUEST: 'LEAVE_REQUEST',
	PAYSLIP: 'PAYSLIP',
	OVERTIME_REQUEST: 'OVERTIME_REQUEST',
	APPROVAL_WORKFLOW: 'APPROVAL_WORKFLOW',
	APPROVAL_INSTANCE: 'APPROVAL_INSTANCE',
	LEAVE_BALANCE: 'LEAVE_BALANCE',
	LEAVE_TYPE: 'LEAVE_TYPE',
	PAYROLL_SETTINGS: 'PAYROLL_SETTINGS',
	PAY_COMPONENT: 'PAY_COMPONENT',
	EMPLOYEE_COMPENSATION: 'EMPLOYEE_COMPENSATION',
	RECURRING_PAY_COMPONENT: 'RECURRING_PAY_COMPONENT',
	PAYROLL_PERIOD: 'PAYROLL_PERIOD',
	PAYROLL_RUN: 'PAYROLL_RUN',
	PAYROLL_ADJUSTMENT: 'PAYROLL_ADJUSTMENT',
	PAYROLL_SCHEDULE: 'PAYROLL_SCHEDULE',
	PAYROLL_RULE: 'PAYROLL_RULE',
	STATUTORY_RULE: 'STATUTORY_RULE',
	EMPLOYEE_STATUTORY_PROFILE: 'EMPLOYEE_STATUTORY_PROFILE',
	EMPLOYEE_PAYMENT_PROFILE: 'EMPLOYEE_PAYMENT_PROFILE',
	EMPLOYEE_BANK_ACCOUNT: 'EMPLOYEE_BANK_ACCOUNT',
	PAYROLL_PAYMENT_BATCH: 'PAYROLL_PAYMENT_BATCH',
	PAYROLL_PAYMENT_ITEM: 'PAYROLL_PAYMENT_ITEM',
	BANK_EXPORT_PROFILE: 'BANK_EXPORT_PROFILE',
	PAYMENT_RECONCILIATION_IMPORT: 'PAYMENT_RECONCILIATION_IMPORT',
	PAYMENT_RECONCILIATION_PROFILE: 'PAYMENT_RECONCILIATION_PROFILE',
	GL_ACCOUNT: 'GL_ACCOUNT',
	PAYROLL_ACCOUNTING_RULE_SET: 'PAYROLL_ACCOUNTING_RULE_SET',
	PAYROLL_JOURNAL: 'PAYROLL_JOURNAL',
	ACCOUNTING_EXPORT_PROFILE: 'ACCOUNTING_EXPORT_PROFILE',
	REPORT: 'REPORT'
} as const;
export type AuditEntityType = (typeof AuditEntity)[keyof typeof AuditEntity];

export interface AuditEventInput {
	action: AuditActionCode | (string & {});
	entityType: AuditEntityType | (string & {});
	/** a numeric entity id is stored as String(id) (numeric-ID migration); string keys (reports) as-is */
	entityId?: number | string | null;
	companyId?: number | null;
	employeeId?: number | null;
	/** defaults to the authenticated user of the current request */
	actorUserId?: number | null;
	/** already-normalised diff (see buildChanges) — sanitised again here */
	changes?: Record<string, unknown> | null;
	/** small set of SAFE identifiers — never request bodies, reasons or secrets */
	metadata?: Record<string, unknown> | null;
	/** override the ambient request context (tests / background jobs) */
	requestContext?: Partial<RequestContext>;
}

export async function writeAuditEvent(db: AuditDb, input: AuditEventInput) {
	const ambient = getRequestContext();
	const ctx = { ...ambient, ...input.requestContext };
	const changes = input.changes ? sanitizeForAudit(input.changes) : null;
	const metadata = input.metadata ? sanitizeForAudit(input.metadata) : null;
	return db.auditEvent.create({
		data: {
			action: input.action,
			entityType: input.entityType,
			entityId:
				input.entityId === undefined || input.entityId === null ? null : String(input.entityId),
			companyId: input.companyId ?? null,
			employeeId: input.employeeId ?? null,
			actorUserId: input.actorUserId !== undefined ? input.actorUserId : (ctx.actorUserId ?? null),
			requestId: ctx.requestId ?? null,
			ipAddress: ctx.ipAddress ?? null,
			userAgent: ctx.userAgent ?? null,
			changesJson: changes === null ? Prisma.DbNull : changes,
			metadataJson: metadata === null ? Prisma.DbNull : metadata
		},
		select: { id: true }
	});
}

/** Picks the harmless "what is this row" fields for audit metadata (never the whole row). */
export function safeLabel(row: object): Record<string, unknown> {
	const out: Record<string, unknown> = {};
	for (const key of ['code', 'nameLao', 'name', 'date', 'employeeCode']) {
		const v = (row as Record<string, unknown>)[key];
		if (v !== undefined && v !== null && typeof v !== 'object') out[key] = v;
		else if (v instanceof Date) out[key] = v.toISOString().slice(0, 10);
	}
	return out;
}

export interface AuditUpdatedInput {
	action: AuditActionCode | (string & {});
	entityType: AuditEntityType | (string & {});
	entityId: number | string;
	companyId?: number | null;
	employeeId?: number | null;
	before: object;
	after: object;
	/** the fields the request could change (usually Object.keys(input)) */
	fields: readonly string[];
	metadata?: Record<string, unknown> | null;
}

/** Writes an "updated" event with a normalised before/after diff — or nothing if nothing changed. */
export async function auditUpdated(db: AuditDb, input: AuditUpdatedInput) {
	const changes = buildChanges(
		input.before as Record<string, unknown>,
		input.after as Record<string, unknown>,
		input.fields
	);
	if (!changes) return null;
	return writeAuditEvent(db, {
		action: input.action,
		entityType: input.entityType,
		entityId: input.entityId,
		companyId: input.companyId,
		employeeId: input.employeeId,
		changes,
		metadata: input.metadata
	});
}
