import { z } from 'zod';
import { positiveMoneyField } from '../lib/money.js';
import {
	codeField,
	idField,
	nameField,
	nullableText,
	optionalId,
	orgStatusEnum,
	paginationQuerySchema
} from './common.schema.js';
import { dateField, optionalDateField } from './employee.schema.js';

/** ISO-4217 style 3-letter code (LAK, USD, THB …). Upper-cased; no conversion is ever done. */
export const currencyCodeField = () =>
	z
		.string()
		.trim()
		.toUpperCase()
		.regex(/^[A-Z]{3}$/, 'ສະກຸນເງິນຕ້ອງເປັນລະຫັດ 3 ຕົວອັກສອນ (ເຊັ່ນ LAK, USD, THB)');

export const payFrequencyEnum = z.enum(['MONTHLY']);
export const payComponentTypeEnum = z.enum(['EARNING', 'DEDUCTION']);
/** Phase 12B - statutory treatment; deliberately never inferred from `category` */
export const pitTreatmentEnum = z.enum(['TAXABLE', 'EXEMPT']);
export const socialSecurityTreatmentEnum = z.enum(['INCLUDED', 'EXCLUDED']);
export const payComponentCategoryEnum = z.enum([
	'ALLOWANCE',
	'BONUS',
	'OTHER_EARNING',
	'DEDUCTION',
	'OTHER_DEDUCTION'
]);
const EARNING_CATEGORIES = ['ALLOWANCE', 'BONUS', 'OTHER_EARNING'];
const DEDUCTION_CATEGORIES = ['DEDUCTION', 'OTHER_DEDUCTION'];

// ---------- settings ----------

export const payrollSettingsQuerySchema = z.object({ companyId: idField('ກະລຸນາເລືອກບໍລິສັດ') });
export const payrollSettingsUpdateSchema = z
	.object({
		currencyCode: currencyCodeField(),
		payFrequency: payFrequencyEnum.default('MONTHLY'),
		periodNamingPattern: nullableText(100),
		/** Phase 13 — omitted = keep the current mode (DIRECT for a new settings row) */
		approvalMode: z.enum(['DIRECT', 'WORKFLOW']).optional()
	})
	.strict();
export type PayrollSettingsUpdateInput = z.infer<typeof payrollSettingsUpdateSchema>;

// ---------- pay components ----------

export const payComponentListQuerySchema = paginationQuerySchema.extend({
	companyId: optionalId(),
	type: payComponentTypeEnum.optional(),
	status: orgStatusEnum.optional(),
	search: z.string().trim().max(120).optional()
});
export type PayComponentListQuery = z.infer<typeof payComponentListQuerySchema>;

const categoryMatchesType = (d: { type?: string; category?: string }) =>
	!d.type ||
	!d.category ||
	(d.type === 'EARNING' ? EARNING_CATEGORIES : DEDUCTION_CATEGORIES).includes(d.category);
const CATEGORY_MESSAGE = 'ໝວດໝູ່ບໍ່ສອດຄ່ອງກັບປະເພດລາຍຮັບ/ລາຍຈ່າຍ';

export const payComponentCreateSchema = z
	.object({
		companyId: idField('ກະລຸນາເລືອກບໍລິສັດ'),
		code: codeField(30),
		nameLao: nameField(150),
		nameEnglish: nullableText(150),
		type: payComponentTypeEnum,
		category: payComponentCategoryEnum,
		isRecurring: z.boolean().default(true),
		description: nullableText(255),
		pitTreatment: pitTreatmentEnum.default('TAXABLE'),
		socialSecurityTreatment: socialSecurityTreatmentEnum.default('INCLUDED'),
		status: orgStatusEnum.default('ACTIVE')
	})
	.strict()
	.refine(categoryMatchesType, { message: CATEGORY_MESSAGE, path: ['category'] });
export type PayComponentCreateInput = z.infer<typeof payComponentCreateSchema>;

/** type and companyId are fixed after creation (they decide the arithmetic direction of past results). */
export const payComponentUpdateSchema = z
	.object({
		nameLao: nameField(150).optional(),
		nameEnglish: nullableText(150),
		category: payComponentCategoryEnum.optional(),
		isRecurring: z.boolean().optional(),
		description: nullableText(255),
		pitTreatment: pitTreatmentEnum.optional(),
		socialSecurityTreatment: socialSecurityTreatmentEnum.optional(),
		status: orgStatusEnum.optional()
	})
	.strict()
	.refine((d) => Object.keys(d).length > 0, { message: 'ບໍ່ມີຂໍ້ມູນທີ່ຈະອັບເດດ' });
export type PayComponentUpdateInput = z.infer<typeof payComponentUpdateSchema>;

// ---------- compensation ----------

export const compensationCreateSchema = z
	.object({
		baseSalary: positiveMoneyField(),
		effectiveFrom: dateField(),
		reason: nullableText(500),
		/** optional — when sent it must equal the company payroll currency (never converted) */
		currencyCode: currencyCodeField().optional()
	})
	.strict();
export type CompensationCreateInput = z.infer<typeof compensationCreateSchema>;

export const recurringAssignSchema = z
	.object({
		payComponentId: idField('ກະລຸນາເລືອກລາຍການ'),
		amount: positiveMoneyField(),
		effectiveFrom: dateField(),
		note: nullableText(500)
	})
	.strict();
export type RecurringAssignInput = z.infer<typeof recurringAssignSchema>;

export const recurringEndSchema = z.object({ effectiveTo: dateField() }).strict();
export type RecurringEndInput = z.infer<typeof recurringEndSchema>;

// ---------- periods ----------

export const periodListQuerySchema = paginationQuerySchema.extend({
	companyId: optionalId(),
	/** only the periods generated by this schedule */
	scheduleId: optionalId(),
	year: z.coerce.number().int().min(2000).max(2100).optional(),
	status: z.enum(['OPEN', 'CLOSED']).optional()
});
export type PeriodListQuery = z.infer<typeof periodListQuerySchema>;

const periodDatesValid = (d: { startDate?: Date; endDate?: Date; payDate?: Date }) =>
	!d.startDate || !d.endDate || d.endDate >= d.startDate;
const payDateValid = (d: { endDate?: Date; payDate?: Date }) =>
	!d.endDate || !d.payDate || d.payDate >= d.endDate;

export const periodCreateSchema = z
	.object({
		companyId: idField('ກະລຸນາເລືອກບໍລິສັດ'),
		code: codeField(30),
		name: nameField(150),
		startDate: dateField(),
		endDate: dateField(),
		payDate: dateField()
	})
	.strict()
	.refine(periodDatesValid, { message: 'ວັນສິ້ນສຸດຕ້ອງບໍ່ກ່ອນວັນເລີ່ມ', path: ['endDate'] })
	.refine(payDateValid, { message: 'ວັນຈ່າຍຕ້ອງບໍ່ກ່ອນວັນສິ້ນສຸດງວດ', path: ['payDate'] });
export type PeriodCreateInput = z.infer<typeof periodCreateSchema>;

export const periodUpdateSchema = z
	.object({
		name: nameField(150).optional(),
		startDate: optionalDateField(),
		endDate: optionalDateField(),
		payDate: optionalDateField()
	})
	.strict()
	.refine((d) => Object.keys(d).length > 0, { message: 'ບໍ່ມີຂໍ້ມູນທີ່ຈະອັບເດດ' });
export type PeriodUpdateInput = z.infer<typeof periodUpdateSchema>;

// ---------- runs ----------

export const runListQuerySchema = paginationQuerySchema.extend({
	companyId: optionalId(),
	periodId: optionalId(),
	status: z.enum(['DRAFT', 'CALCULATED', 'FINALIZED']).optional(),
	year: z.coerce.number().int().min(2000).max(2100).optional()
});
export type RunListQuery = z.infer<typeof runListQuerySchema>;

export const runCreateSchema = z
	.object({
		companyId: idField('ກະລຸນາເລືອກບໍລິສັດ'),
		periodId: idField('ກະລຸນາເລືອກງວດ')
	})
	.strict();
export type RunCreateInput = z.infer<typeof runCreateSchema>;

/** `expectedNetPay` (optional) is the net total the user saw when confirming — a stale confirmation is refused. */
export const runFinalizeSchema = z
	.object({ expectedNetPay: z.string().trim().max(30).optional() })
	.strict();
export type RunFinalizeInput = z.infer<typeof runFinalizeSchema>;

export const resultListQuerySchema = paginationQuerySchema.extend({
	calculationStatus: z.enum(['READY', 'BLOCKED']).optional(),
	departmentId: optionalId(),
	search: z.string().trim().max(120).optional()
});
export type ResultListQuery = z.infer<typeof resultListQuerySchema>;

export const adjustmentCreateSchema = z
	.object({
		payComponentId: z.preprocess((v) => (v === '' ? undefined : v), optionalId()),
		type: payComponentTypeEnum,
		code: codeField(30),
		nameLao: nameField(150),
		amount: positiveMoneyField(),
		reason: z.string().trim().min(3, 'ກະລຸນາລະບຸເຫດຜົນ').max(500)
	})
	.strict();
export type AdjustmentCreateInput = z.infer<typeof adjustmentCreateSchema>;
