import PDFDocument from 'pdfkit';
import { Prisma } from '@prisma/client';
import { FONTS, formatAmount } from '../payslipPdf.js';
import type { ColumnDef, DetailRow } from './reportDefinitions.js';
import { displayValue, isNumeric } from './reportFormat.js';

/**
 * Phase 17B PDF — A4 report table with the Phase 13 self-hosted fonts (Noto Sans Lao for Lao code points,
 * Noto Sans for everything else; embedded as subsets, never served separately).
 *
 * LAYOUT (learning from the Phase 13 right-alignment bug): pdfkit's `continued` runs are NOT used. Every
 * cell is laid out here — Lao is segmented into words with Intl.Segmenter (Lao has no spaces between
 * words), each run is measured in ITS font, lines are wrapped to the column width (an over-long word is
 * split between grapheme clusters, never inside one), and each run is drawn at an explicit x with
 * `lineBreak: false`. Money / numbers are right-aligned by measured width, so nothing overlaps.
 * Rows are never split across pages; the table header repeats on every page; the footer carries
 * "Page X / Y" and "Generated by LaoHR"; sensitive reports carry a Confidential mark.
 */
export const PDF_MAX_COLUMNS = 10;

const LAO = /[຀-໿]/;
const INK = '#1f2937';
const MUTED = '#6b7280';
const LINE = '#e5e7eb';
const HEAD_FILL = '#eef2f7';
const TOTAL_FILL = '#f8fafc';

const words = new Intl.Segmenter('lo', { granularity: 'word' });
const graphemes = new Intl.Segmenter('lo', { granularity: 'grapheme' });

type Doc = InstanceType<typeof PDFDocument>;
interface Run {
	lao: boolean;
	t: string;
	w: number;
}
type Line = { runs: Run[]; w: number };

const fontOf = (lao: boolean, bold: boolean) =>
	lao ? (bold ? 'laoBold' : 'lao') : bold ? 'latinBold' : 'latin';

function toRuns(doc: Doc, text: string, size: number, bold: boolean): Run[] {
	const out: { lao: boolean; t: string }[] = [];
	for (const ch of text) {
		const last = out.at(-1);
		const lao = LAO.test(ch) || (ch === ' ' && !!last?.lao);
		if (last && last.lao === lao) last.t += ch;
		else out.push({ lao, t: ch });
	}
	return out.map((r) => ({
		...r,
		w: doc.font(fontOf(r.lao, bold)).fontSize(size).widthOfString(r.t)
	}));
}

const widthOf = (doc: Doc, text: string, size: number, bold: boolean) =>
	toRuns(doc, text, size, bold).reduce((s, r) => s + r.w, 0);

const OPENING = /^[([{“‘«]+$/;
const CLOSING = /^[)\]}”’»,.;:!?%]+$/;

/** Word segments where an opening bracket sticks to the next word and closing punctuation to the previous one. */
export function breakUnits(text: string): string[] {
	const units: string[] = [];
	let carry = '';
	for (const { segment } of words.segment(text)) {
		if (OPENING.test(segment)) carry += segment;
		else if (CLOSING.test(segment) && units.length && !carry) units[units.length - 1] += segment;
		else {
			units.push(carry + segment);
			carry = '';
		}
	}
	if (carry) units.push(carry);
	return units;
}

/** Wraps mixed Lao / Latin text into lines no wider than `width`. */
function layout(doc: Doc, text: string, width: number, size: number, bold: boolean): Line[] {
	const lines: string[] = [];
	let cur = '';
	const push = () => {
		if (cur.trim() !== '') lines.push(cur.trimEnd());
		cur = '';
	};
	for (const segment of breakUnits(text)) {
		if (widthOf(doc, cur + segment, size, bold) <= width) {
			cur += segment;
			continue;
		}
		if (segment.trim() === '') {
			push();
			continue;
		}
		if (widthOf(doc, segment, size, bold) <= width) {
			push();
			cur = segment;
			continue;
		}
		// a single word wider than the column: break between grapheme clusters
		for (const { segment: g } of graphemes.segment(segment)) {
			if (widthOf(doc, cur + g, size, bold) > width && cur !== '') push();
			cur += g;
		}
	}
	push();
	return (lines.length ? lines : ['']).map((l) => {
		const runs = toRuns(doc, l, size, bold);
		return { runs, w: runs.reduce((s, r) => s + r.w, 0) };
	});
}

function drawLines(
	doc: Doc,
	lines: Line[],
	x: number,
	y: number,
	width: number,
	o: { size: number; bold: boolean; color: string; align: 'left' | 'right'; lineHeight: number }
) {
	doc.fillColor(o.color);
	lines.forEach((line, i) => {
		let cx = o.align === 'right' ? x + width - line.w : x;
		for (const r of line.runs) {
			doc.font(fontOf(r.lao, o.bold)).fontSize(o.size);
			doc.text(r.t, cx, y + i * o.lineHeight, { lineBreak: false });
			cx += r.w;
		}
	});
}

const WEIGHT: Record<ColumnDef['type'], number> = {
	text: 1.5,
	date: 1,
	datetime: 1.35,
	integer: 0.7,
	minutes: 0.9,
	money: 1.35,
	decimal: 0.8,
	status: 1.3
};
const WIDE = new Set(['description', 'fullName', 'employeeName', 'accountName']);

export interface PdfReportInput {
	title: string;
	sensitive: boolean;
	generatedAt: Date;
	filterLines: string[];
	columns: ColumnDef[];
	rows: DetailRow[];
	/** money columns to total (Decimal) */
	totals: string[];
}

const laosStamp = (d: Date) => {
	const t = new Date(d.getTime() + 7 * 3_600_000).toISOString();
	return `${t.slice(8, 10)}/${t.slice(5, 7)}/${t.slice(0, 4)} ${t.slice(11, 16)}`;
};

export function renderReportPdf(input: PdfReportInput): Promise<Buffer> {
	const landscape = input.columns.length > 4;
	const doc = new PDFDocument({
		size: 'A4',
		layout: landscape ? 'landscape' : 'portrait',
		margins: { top: 36, bottom: 40, left: 36, right: 36 },
		bufferPages: true,
		info: { Title: input.title, Author: 'LaoHR', Creator: 'LaoHR' }
	});
	doc.registerFont('lao', FONTS.lao);
	doc.registerFont('laoBold', FONTS.laoBold);
	doc.registerFont('latin', FONTS.latin);
	doc.registerFont('latinBold', FONTS.latinBold);
	const chunks: Buffer[] = [];
	doc.on('data', (c: Buffer) => chunks.push(c));
	const done = new Promise<Buffer>((resolve, reject) => {
		doc.on('end', () => resolve(Buffer.concat(chunks)));
		doc.on('error', reject);
	});

	const left = doc.page.margins.left;
	const width = doc.page.width - left - doc.page.margins.right;
	const bottom = () => doc.page.height - doc.page.margins.bottom;
	const SIZE = 8;
	const LH = SIZE * 1.55;
	const PAD_X = 4;
	const PAD_Y = 3.5;

	const text = (
		value: string,
		x: number,
		y: number,
		w: number,
		o: { size?: number; bold?: boolean; color?: string; align?: 'left' | 'right' } = {}
	) => {
		const size = o.size ?? 9;
		const lh = size * 1.5;
		const lines = layout(doc, value, w, size, o.bold ?? false);
		drawLines(doc, lines, x, y, w, {
			size,
			bold: o.bold ?? false,
			color: o.color ?? INK,
			align: o.align ?? 'left',
			lineHeight: lh
		});
		return lines.length * lh;
	};

	// ---------- column widths (by type, deterministic) ----------
	const weights = input.columns.map((c) => (WIDE.has(c.key) ? 2.2 : WEIGHT[c.type]));
	const totalWeight = weights.reduce((a, b) => a + b, 0);
	const colW = weights.map((w) => (w / totalWeight) * width);
	const colX = colW.map((_, i) => left + colW.slice(0, i).reduce((a, b) => a + b, 0));

	// ---------- first-page header ----------
	let y = doc.page.margins.top;
	text('LaoHR', left, y, width / 2, { size: 13, bold: true, color: '#1d4ed8' });
	if (input.sensitive) {
		text('ຂໍ້ມູນລັບ · Confidential', left + width / 2, y + 2, width / 2, {
			size: 8.5,
			bold: true,
			color: '#b91c1c',
			align: 'right'
		});
	}
	y += 20;
	y += text(input.title, left, y, width, { size: 14, bold: true });
	y += text(
		`ສ້າງເມື່ອ ${laosStamp(input.generatedAt)} (Asia/Vientiane) · ${input.rows.length} ແຖວ`,
		left,
		y + 2,
		width,
		{ size: 8.5, color: MUTED }
	);
	for (const f of input.filterLines) y += text(f, left, y + 2, width, { size: 8.5, color: MUTED });
	y += 10;

	// ---------- table ----------
	const headerLines = input.columns.map((c, i) =>
		layout(doc, c.label, colW[i]! - 2 * PAD_X, SIZE, true)
	);
	const headerH = Math.max(...headerLines.map((l) => l.length)) * LH + 2 * PAD_Y;
	const drawHeader = () => {
		doc.rect(left, y, width, headerH).fill(HEAD_FILL);
		input.columns.forEach((c, i) =>
			drawLines(doc, headerLines[i]!, colX[i]! + PAD_X, y + PAD_Y, colW[i]! - 2 * PAD_X, {
				size: SIZE,
				bold: true,
				color: INK,
				align: isNumeric(c) ? 'right' : 'left',
				lineHeight: LH
			})
		);
		y += headerH;
	};
	const newPage = () => {
		doc.addPage();
		y = doc.page.margins.top;
		text(input.title, left, y, width, { size: 9, bold: true, color: MUTED });
		y += 18;
		drawHeader();
	};
	const drawRow = (cells: string[], o: { bold: boolean; fill?: string }) => {
		const laid = cells.map((v, i) => layout(doc, v, colW[i]! - 2 * PAD_X, SIZE, o.bold));
		const h = Math.max(...laid.map((l) => l.length)) * LH + 2 * PAD_Y;
		if (y + h > bottom()) newPage(); // a row is never split across pages
		if (o.fill) doc.rect(left, y, width, h).fill(o.fill);
		laid.forEach((lines, i) =>
			drawLines(doc, lines, colX[i]! + PAD_X, y + PAD_Y, colW[i]! - 2 * PAD_X, {
				size: SIZE,
				bold: o.bold,
				color: INK,
				align: isNumeric(input.columns[i]!) ? 'right' : 'left',
				lineHeight: LH
			})
		);
		doc
			.moveTo(left, y + h)
			.lineTo(left + width, y + h)
			.lineWidth(0.5)
			.strokeColor(LINE)
			.stroke();
		y += h;
	};

	drawHeader();
	if (input.rows.length === 0) {
		drawRow(
			input.columns.map((_, i) => (i === 0 ? 'ບໍ່ມີຂໍ້ມູນຕາມຕົວກອງ' : '')),
			{ bold: false }
		);
	}
	for (const row of input.rows) {
		drawRow(
			input.columns.map((c) => displayValue(c, row[c.key] ?? null)),
			{ bold: false }
		);
	}

	// ---------- totals (Decimal) ----------
	const totalKeys = input.columns.filter((c) => input.totals.includes(c.key));
	if (totalKeys.length > 0 && input.rows.length > 0) {
		const sums = new Map(
			totalKeys.map((c) => [
				c.key,
				input.rows.reduce(
					(s, r) => s.plus(new Prisma.Decimal(String(r[c.key] ?? '0'))),
					new Prisma.Decimal(0)
				)
			])
		);
		const labelAt = input.columns.findIndex((c) => !input.totals.includes(c.key));
		drawRow(
			input.columns.map((c, i) =>
				sums.has(c.key)
					? formatAmount(sums.get(c.key)!.toFixed(2))
					: i === labelAt
						? 'ລວມທັງໝົດ'
						: ''
			),
			{ bold: true, fill: TOTAL_FILL }
		);
	}

	// ---------- footer on every page ----------
	const range = doc.bufferedPageRange();
	for (let i = 0; i < range.count; i++) {
		doc.switchToPage(range.start + i);
		const savedBottom = doc.page.margins.bottom;
		doc.page.margins.bottom = 0; // writing inside the bottom margin must not add a page
		const fy = doc.page.height - 26;
		text(`Generated by LaoHR${input.sensitive ? ' · Confidential' : ''}`, left, fy, width / 2, {
			size: 7.5,
			color: MUTED
		});
		text(`Page ${i + 1} / ${range.count}`, left + width / 2, fy, width / 2, {
			size: 7.5,
			color: MUTED,
			align: 'right'
		});
		doc.page.margins.bottom = savedBottom;
	}
	doc.end();
	return done;
}

/** Test / diagnostics: lays out one cell exactly like the renderer and returns each line's width. */
export function measureCell(text: string, width: number, size = 8, bold = false): number[] {
	const doc = new PDFDocument({ size: 'A4', autoFirstPage: true });
	doc.registerFont('lao', FONTS.lao);
	doc.registerFont('laoBold', FONTS.laoBold);
	doc.registerFont('latin', FONTS.latin);
	doc.registerFont('latinBold', FONTS.latinBold);
	const widths = layout(doc, text, width, size, bold).map((l) => l.w);
	doc.end();
	return widths;
}
